version: "3"

services: 
    odoo:
        build: 
            context: .
            dockerfile: OdooStock-Dockerfile
        depends_on: 
            - db
        ports: 
            - "8069:8069"
        environment: 
            - HOST=db
            - USER=odoo
            - PASSWORD=odoo
            - NAME=odoo
    db:
        image: postgres:11
        ports:
            - "5555:5432"
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
        volumes:
            - odoo-db-data:/var/lib/postgresql/
    
volumes: 
    odoo-db-data:
    pgadmin:
